version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    command: 'php artisan serve --host=0.0.0.0'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "jorge"
      MYSQL_PASSWORD: "jorge"
      MYSQL_ROOT: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  db:
    driver: local
  

