version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    command: 'php artisan serve --host=0.0.0.0'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
      
volumes:
  db:
    driver: local
  

